In [3]:
#import pandas
import pandas as pd

In [4]:
#bring in dataframe
df = pd.read_csv(r"C:\Users\Burgundy\Documents\Data Analysis Projects\Project7-MovieData\MovieAndTVData.csv")
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

In [5]:
#checking number of null values and data types for each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MOVIES    9999 non-null   object
 1   YEAR      9355 non-null   object
 2   GENRE     9919 non-null   object
 3   RATING    8179 non-null   float64
 4   ONE-LINE  9999 non-null   object
 5   STARS     9999 non-null   object
 6   VOTES     8179 non-null   object
 7   RunTime   7041 non-null   float64
 8   Gross     460 non-null    object
dtypes: float64(2), object(7)
memory usage: 703.2+ KB

In [6]:
#view non-null values for Gross columns to determine needed formatting
df[df[['Gross']].notna().all(axis=1)]

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
77,The Hitman's Bodyguard,(2017),"\nAction, Comedy, Crime",6.9,"\nThe world's top bodyguard gets a new client,...",\n Director:\nPatrick Hughes\n| \n Stars...,"205,979",118.0,$75.47M
85,Jurassic Park,(1993),"\nAction, Adventure, Sci-Fi",8.1,\nA pragmatic paleontologist visiting an almos...,\n Director:\nSteven Spielberg\n| \n Sta...,"897,444",127.0,$402.45M
95,Don't Breathe,(2016),"\nCrime, Horror, Thriller",7.1,"\nHoping to walk away with a massive fortune, ...",\n Director:\nFede Alvarez\n| \n Stars:\...,"237,601",88.0,$89.22M
111,The Lord of the Rings: The Fellowship of the Ring,(2001),"\nAction, Adventure, Drama",8.8,\nA meek Hobbit from the Shire and eight compa...,\n Director:\nPeter Jackson\n| \n Stars:...,"1,713,028",178.0,$315.54M
125,Escape Room,(I) (2019),"\nAction, Adventure, Horror",6.4,\nSix strangers find themselves in a maze of d...,\n Director:\nAdam Robitel\n| \n Stars:\...,"99,351",99.0,$57.01M
...,...,...,...,...,...,...,...,...,...
5750,Vidal Sassoon: The Movie,(2010),\nDocumentary,6.5,\nVidal Sassoon is more than just a hairdresse...,\n Director:\nCraig Teper\n| \n Stars:\n...,245,90.0,$0.09M
5770,Men at Lunch,(2012),"\nDocumentary, Mystery",6.3,"\nThe story of ""Lunch atop a Skyscraper,"" the ...",\n Director:\nSeán Ó Cualáin\n| \n Stars...,331,75.0,$0.00M
5835,Decoding Deepak,(2012),\nDocumentary,5.5,"\nDeepak Chopra's son, Gotham, spends a year t...",\n Director:\nGotham Chopra\n| \n Stars:...,124,83.0,$0.01M
6056,Theo Who Lived,(2016),\nDocumentary,6.8,\nA documentary on American journalist Theo Pa...,\n Director:\nDavid Schisgall\n| \n Star...,111,86.0,$0.01M
6292,Southern Justice,(2006),"\nAction, Adventure, Thriller",3.1,"\nM.D. Selig's feature thriller, SOUTHERN JUST...",\n Director:\nM.D. Selig\n| \n Stars:\nM...,126,96.0,$0.14M

In [7]:
#Remove not needed columns
df = df.drop(columns = ["STARS", "ONE-LINE", "VOTES"] )
df

,MOVIES,YEAR,GENRE,RATING,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,NaN,NaN
...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,NaN,NaN
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,NaN,NaN
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,NaN,NaN

In [8]:
#Remove unnecessary duplicate values
df = df.drop_duplicates()
df

,MOVIES,YEAR,GENRE,RATING,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,NaN,NaN
...,...,...,...,...,...,...
9975,Ultraman,(2019– ),"\nAnimation, Action, Adventure",NaN,NaN,NaN
9979,Never Have I Ever,(2020– ),\nComedy,8.8,NaN,NaN
9993,Totenfrau,(2022– ),"\nDrama, Thriller",NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,NaN,NaN

In [9]:
#Create check point

In [10]:
#Reformat Gross Column
df["Gross"] = df["Gross"].str.strip("$BM")
df[df[['Gross']].notna().all(axis=1)]

C:\Users\Burgundy\AppData\Local\Temp\ipykernel_15496\2321032847.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gross"] = df["Gross"].str.strip("$BM")

,MOVIES,YEAR,GENRE,RATING,RunTime,Gross
77,The Hitman's Bodyguard,(2017),"\nAction, Comedy, Crime",6.9,118.0,75.47
85,Jurassic Park,(1993),"\nAction, Adventure, Sci-Fi",8.1,127.0,402.45
95,Don't Breathe,(2016),"\nCrime, Horror, Thriller",7.1,88.0,89.22
111,The Lord of the Rings: The Fellowship of the Ring,(2001),"\nAction, Adventure, Drama",8.8,178.0,315.54
125,Escape Room,(I) (2019),"\nAction, Adventure, Horror",6.4,99.0,57.01
...,...,...,...,...,...,...
5750,Vidal Sassoon: The Movie,(2010),\nDocumentary,6.5,90.0,0.09
5770,Men at Lunch,(2012),"\nDocumentary, Mystery",6.3,75.0,0.00
5835,Decoding Deepak,(2012),\nDocumentary,5.5,83.0,0.01
6056,Theo Who Lived,(2016),\nDocumentary,6.8,86.0,0.01
6292,Southern Justice,(2006),"\nAction, Adventure, Thriller",3.1,96.0,0.14

In [11]:
#Change Gross column datatype to float
df['Gross'] = df['Gross'].astype('float')
df[df[['Gross']].notna().all(axis=1)]

C:\Users\Burgundy\AppData\Local\Temp\ipykernel_15496\3677233049.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gross'] = df['Gross'].astype('float')

,MOVIES,YEAR,GENRE,RATING,RunTime,Gross
77,The Hitman's Bodyguard,(2017),"\nAction, Comedy, Crime",6.9,118.0,75.47
85,Jurassic Park,(1993),"\nAction, Adventure, Sci-Fi",8.1,127.0,402.45
95,Don't Breathe,(2016),"\nCrime, Horror, Thriller",7.1,88.0,89.22
111,The Lord of the Rings: The Fellowship of the Ring,(2001),"\nAction, Adventure, Drama",8.8,178.0,315.54
125,Escape Room,(I) (2019),"\nAction, Adventure, Horror",6.4,99.0,57.01
...,...,...,...,...,...,...
5750,Vidal Sassoon: The Movie,(2010),\nDocumentary,6.5,90.0,0.09
5770,Men at Lunch,(2012),"\nDocumentary, Mystery",6.3,75.0,0.00
5835,Decoding Deepak,(2012),\nDocumentary,5.5,83.0,0.01
6056,Theo Who Lived,(2016),\nDocumentary,6.8,86.0,0.01
6292,Southern Justice,(2006),"\nAction, Adventure, Thriller",3.1,96.0,0.14

In [12]:
#Remove unwanted characters from Genre column
df["GENRE"] = df["GENRE"].str.strip("\n")
df

C:\Users\Burgundy\AppData\Local\Temp\ipykernel_15496\2149096397.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GENRE"] = df["GENRE"].str.strip("\n")

,MOVIES,YEAR,GENRE,RATING,RunTime,Gross
0,Blood Red Sky,(2021),"Action, Horror, Thriller",6.1,121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"Animation, Action, Adventure",5.0,25.0,NaN
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",8.2,44.0,NaN
3,Rick and Morty,(2013– ),"Animation, Adventure, Comedy",9.2,23.0,NaN
4,Army of Thieves,(2021),"Action, Crime, Horror",NaN,NaN,NaN
...,...,...,...,...,...,...
9975,Ultraman,(2019– ),"Animation, Action, Adventure",NaN,NaN,NaN
9979,Never Have I Ever,(2020– ),Comedy,8.8,NaN,NaN
9993,Totenfrau,(2022– ),"Drama, Thriller",NaN,NaN,NaN
9995,Arcane,(2021– ),"Animation, Action, Adventure",NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"Documentary, Sport",NaN,NaN,NaN

In [13]:
#Remove end year from TV shows
df["YEAR"] = df["YEAR"].str.split("–").str[0]
df

C:\Users\Burgundy\AppData\Local\Temp\ipykernel_15496\1798950188.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["YEAR"] = df["YEAR"].str.split("–").str[0]

,MOVIES,YEAR,GENRE,RATING,RunTime,Gross
0,Blood Red Sky,(2021),"Action, Horror, Thriller",6.1,121.0,NaN
1,Masters of the Universe: Revelation,(2021,"Animation, Action, Adventure",5.0,25.0,NaN
2,The Walking Dead,(2010,"Drama, Horror, Thriller",8.2,44.0,NaN
3,Rick and Morty,(2013,"Animation, Adventure, Comedy",9.2,23.0,NaN
4,Army of Thieves,(2021),"Action, Crime, Horror",NaN,NaN,NaN
...,...,...,...,...,...,...
9975,Ultraman,(2019,"Animation, Action, Adventure",NaN,NaN,NaN
9979,Never Have I Ever,(2020,Comedy,8.8,NaN,NaN
9993,Totenfrau,(2022,"Drama, Thriller",NaN,NaN,NaN
9995,Arcane,(2021,"Animation, Action, Adventure",NaN,NaN,NaN
9996,Heart of Invictus,(2022,"Documentary, Sport",NaN,NaN,NaN

In [14]:
#Remove unwanted characters from Year column
df["YEAR"] = df["YEAR"].str.strip("()")
df

C:\Users\Burgundy\AppData\Local\Temp\ipykernel_15496\2001352314.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["YEAR"] = df["YEAR"].str.strip("()")

,MOVIES,YEAR,GENRE,RATING,RunTime,Gross
0,Blood Red Sky,2021,"Action, Horror, Thriller",6.1,121.0,NaN
1,Masters of the Universe: Revelation,2021,"Animation, Action, Adventure",5.0,25.0,NaN
2,The Walking Dead,2010,"Drama, Horror, Thriller",8.2,44.0,NaN
3,Rick and Morty,2013,"Animation, Adventure, Comedy",9.2,23.0,NaN
4,Army of Thieves,2021,"Action, Crime, Horror",NaN,NaN,NaN
...,...,...,...,...,...,...
9975,Ultraman,2019,"Animation, Action, Adventure",NaN,NaN,NaN
9979,Never Have I Ever,2020,Comedy,8.8,NaN,NaN
9993,Totenfrau,2022,"Drama, Thriller",NaN,NaN,NaN
9995,Arcane,2021,"Animation, Action, Adventure",NaN,NaN,NaN
9996,Heart of Invictus,2022,"Documentary, Sport",NaN,NaN,NaN

In [15]:
#Saved cleaned version of data in a new file
#df.to_excel("Movie Data Cleaned.xlsx")

In [29]:
df["YEAR"] = df["YEAR"].str.replace(r"[a-zA-Z],/\|",'')
df

C:\Users\Burgundy\AppData\Local\Temp\ipykernel_15496\2632818316.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df["YEAR"] = df["YEAR"].str.replace(r"[a-zA-Z],/\|",'')
C:\Users\Burgundy\AppData\Local\Temp\ipykernel_15496\2632818316.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["YEAR"] = df["YEAR"].str.replace(r"[a-zA-Z],/\|",'')

,MOVIES,YEAR,GENRE,RATING,RunTime,Gross
0,Blood Red Sky,2021,"Action, Horror, Thriller",6.1,121.0,NaN
1,Masters of the Universe: Revelation,2021,"Animation, Action, Adventure",5.0,25.0,NaN
2,The Walking Dead,2010,"Drama, Horror, Thriller",8.2,44.0,NaN
3,Rick and Morty,2013,"Animation, Adventure, Comedy",9.2,23.0,NaN
4,Army of Thieves,2021,"Action, Crime, Horror",NaN,NaN,NaN
...,...,...,...,...,...,...
9975,Ultraman,2019,"Animation, Action, Adventure",NaN,NaN,NaN
9979,Never Have I Ever,2020,Comedy,8.8,NaN,NaN
9993,Totenfrau,2022,"Drama, Thriller",NaN,NaN,NaN
9995,Arcane,2021,"Animation, Action, Adventure",NaN,NaN,NaN
9996,Heart of Invictus,2022,"Documentary, Sport",NaN,NaN,NaN

In [30]:
df["YEAR"] = df["YEAR"].str.strip("()")

C:\Users\Burgundy\AppData\Local\Temp\ipykernel_15496\3390716865.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["YEAR"] = df["YEAR"].str.strip("()")

In [36]:
df["YEAR"] = df["YEAR"].str.strip("()")
df["YEAR"].head(50)

C:\Users\Burgundy\AppData\Local\Temp\ipykernel_15496\4106577290.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["YEAR"] = df["YEAR"].str.strip("()")

0       2021
1       2021
2       2010
3       2013
4       2021
5       2020
6       2021
7       2006
8       2020
9       2019
10      2021
11      2016
12      2021
13      2021
14      2011
15      2005
16      2008
17      2017
18      2017
19      2016
20      2021
21      1994
22      2014
23      2013
24      2021
25      2021
26      2013
27      2015
28      2005
29      2013
30      2021
31      2016
32      2013
33      2003
34      2019
35      2009
36     (2018
37      2019
38      2010
39      2013
40      2011
41      2017
42      2015
43      2014
44      2015
45      2011
46      2017
47      2016
48      2021
49      2021
Name: YEAR, dtype: object